### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable with sleep_on_rate_limit

### ISSUE THREAD

**Issue by knyghty** [bear/python-twitter#320]
Failing on master, Python 3.5.1.

Code:
```
import twitter
api = twitter.Api(..., sleep_on_rate_limit=True)
api.GetStatus(123456789)
```

Traceback:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    api.GetStatus(123456789)
  File "/home/tom/.virtualenvs/nlp/lib/python3.5/site-packages/twitter/api.py", line 767, in GetStatus
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "/home/tom/.virtualenvs/nlp/lib/python3.5/site-packages/twitter/api.py", line 4353, in _RequestUrl
    limit = self.CheckRateLimit(url)
  File "/home/tom/.virtualenvs/nlp/lib/python3.5/site-packages/twitter/api.py", line 4191, in CheckRateLimit
    limit = self.rate_limit.get_limit(url)
  File "/home/tom/.virtualenvs/nlp/lib/python3.5/site-packages/twitter/ratelimit.py", line 177, in get_limit
    return EndpointRateLimit(family_rates['limit'],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jeremylow** [comment]
Yeah the regex is wrong for that endpoint since the ID is not part of the path, but the query string. Sorry. Fixing it now.

**Comment by jeremylow** [comment]
PR #321 should fix the issue.

**Comment by jeremylow** [comment]
Merged
