### ISSUE TITLE
wait_on_rate_limit=True sometimes results in an IOError

### ISSUE THREAD

**Issue by zetasyanthis** [bear/python-twitter#359]
After quite a few successful pulls, wait_on_rate_limit=True occasionally bombs out with the following exception. This is on python 2.7.6 and 2.7.11 (Xubuntu 14.04 and 16.04 respectively) with python-twitter 3.1.

The print at the start is an added print of limit.reset since I was trying to see what that value in fact was when the error occurred.

```python
1468178377
Traceback (most recent call last):
  File "./src/myarchive/main.py", line 108, in <module>
    main()
  File "./src/myarchive/main.py", line 81, in main
    username=args.username)
  File "/mnt/bulk/repos/projects/myarchive/src/myarchive/twitterlib.py", line 134, in archive_tweets
    include_entities=True)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 3361, in GetFavorites
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 4753, in _RequestUrl
    time.sleep(int(limit.reset - time.time()))
IOError: [Errno 22] Invalid argument
```

**Comment by jeremylow** [comment]
Yeah looks like we need to catch an IOError because that `limit.reset - time.time()` can return a negative number, which isn't allowed.

**Comment by zetasyanthis** [comment]
Might be better to add a min() with zero, saves a try/except context.  I'll submit a pull request if that's cool. :)
