### ISSUE TITLE
wait_on_rate_limit=True sometimes throws a rate limit error

### ISSUE THREAD

**Issue by zetasyanthis** [bear/python-twitter#369]
I'm not sure if this is a bug, or if the code is actually hitting the rate limit error while checking the rate limit itself.  Either way, it seems to happen fairly frequently when making large amounts of API calls, and seems to take place *after* a long pause caused by hitting the rate limit in the first place.

Example code that causes the explosion can be found over here: https://github.com/zetasyanthis/myarchive. Use hash 3ac8fe84500ca9b7e18b80eccb50d6bdeba06478.
Running ./src/myarchive/main.py --username <YOUR USERNAME> --import-tweets-from-api a few times (deleting the DB in ~/.myarchive/ after each run) will reproduce the issue fairly quickly.

```
Traceback (most recent call last):
  File "./src/myarchive/main.py", line 111, in <module>
    main()
  File "./src/myarchive/main.py", line 79, in main
    username=args.username)
  File "/mnt/bulk/repos/projects/myarchive/src/myarchive/twitterlib.py", line 150, in archive_tweets
    include_entities=True)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 3362, in GetFavorites
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 4688, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 4715, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{u'message': u'Rate limit exceeded', u'code': 88}]
```

**Comment by jeremylow** [comment]
If you're restarting the program after each run, then it could be either since you're getting a new, blank RateLimit object after each one. There's not much we can do about that use case.

**Comment by zetasyanthis** [comment]
Ah, okay. And yes, it's a script currently, and I'm re-running as I debug things... Good to know. I'll close the issue for now.
