### ISSUE TITLE
Not working on MacOS Sierra

### ISSUE THREAD

**Issue by shiftsayan** [bear/python-twitter#404]
I am getting the following error when I try to "import twitter".
```
python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import twitter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.12-intel/egg/twitter/__init__.py", line 56, in <module>
  File "build/bdist.macosx-10.12-intel/egg/twitter/api.py", line 29, in <module>
ImportError: No module named requests
```

**Comment by jeremylow** [comment]
Did you install via 'pip install python-twiiter`?

**Comment by shiftsayan** [comment]
@jeremylow I download the zip, navigated to the directory on GitHub and ran setup.py

**Comment by jeremylow** [comment]
You'll need to install the dependencies first. Run:

`make env`

**Comment by shiftsayan** [comment]
Thanks. It worked by installing via pip.
