### ISSUE TITLE
Cannot install python-twitter: socket.error

### ISSUE THREAD

**Issue by csvoss** [bear/python-twitter#406]
I am unable to get `pip install python-twitter` to successfully install this package from within my virtual machine, although I can install other pip packages successfully.

To reproduce:
* Install Vagrant and Virtualbox
* `vagrant up` with ubuntu/trusty64
* `vagrant ssh`
* `pip install urllib3[secure]` (without this, the same error occurs, but with an extra `InsecurePlatformWarning`)
* `pip install python-twitter`

The error itself:
```
$ pip install python-twitter
Downloading/unpacking python-twitter
  Downloading python-twitter-3.1.tar.gz (80kB): 80kB downloaded
  Running setup.py (path:/tmp/pip_build_vagrant/python-twitter/setup.py) egg_info for package python-twitter
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_vagrant/python-twitter/setup.py", line 75, in <module>
        'Programming Language :: Python :: 3.5',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 604, in easy_install
        self.local_index
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 602, in fetch_distribution
        return dist.clone(location=self.download(dist.location, tmpdir))
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 518, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 766, in _download_url
        return self._attempt_download(url, filename)
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 772, in _attempt_download
        headers = self._download_to(url, filename)
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 682, in _download_to
        block = fp.read(bs)
      File "/usr/lib/python2.7/socket.py", line 380, in read
        data = self._sock.recv(left)
      File "/usr/lib/python2.7/httplib.py", line 573, in read
        s = self.fp.read(amt)
      File "/usr/lib/python2.7/socket.py", line 380, in read
        data = self._sock.recv(left)
      File "/usr/lib/python2.7/ssl.py", line 341, in recv
        return self.read(buflen)
      File "/usr/lib/python2.7/ssl.py", line 260, in read
        return self._sslobj.read(len)
    socket.error: [Errno 104] Connection reset by peer
```

**Comment by csvoss** [comment]
Manual fix:

* run `pip install pytest-runner`
* then rerun `pip install python-twitter`

**Comment by jeremylow** [comment]
Checking this out, but unable to reproduce:

```bash
$ vagrant init
$ vim Vagrantfile # change box to ubuntu/trusty64
$ vagrant ssh
$ sudo apt-get update
$ sudo apt-get install python-pip
$ pip install python-twitter
```

Using your branch of zulip (https://github.com/csvoss/zulip/commit/233665fefaecaf128d4f12cc9c822c4956fad58d):

```bash
$ mkdir test
$ cd test
$ git clone git@github.com:csvoss/zulip.git
$ cd zulip
$ git reset HEAD~1 --hard
$ vagrant up
# a million things install
$ vagrant ssh
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-101-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Sun Nov 20 14:24:12 UTC 2016

  System load:  0.27              Processes:           93
  Usage of /:   3.6% of 39.34GB   Users logged in:     0
  Memory usage: 6%                IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.

New release '16.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


(zulip-venv)vagrant@vagrant-ubuntu-trusty-64:~$ pip install python-twitter
Requirement already satisfied: python-twitter in /srv/zulip-venv-cache/a70a26391d4955d458aa1119a2d90bb743d6d1c3/zulip-venv/lib/python2.7/site-packages
Requirement already satisfied: future in /srv/zulip-venv-cache/a70a26391d4955d458aa1119a2d90bb743d6d1c3/zulip-venv/lib/python2.7/site-packages (from python-twitter)
Requirement already satisfied: requests in /srv/zulip-venv-cache/a70a26391d4955d458aa1119a2d90bb743d6d1c3/zulip-venv/lib/python2.7/site-packages (from python-twitter)
Requirement already satisfied: requests-oauthlib in /srv/zulip-venv-cache/a70a26391d4955d458aa1119a2d90bb743d6d1c3/zulip-venv/lib/python2.7/site-packages (from python-twitter)
Requirement already satisfied: oauthlib>=0.6.2 in /srv/zulip-venv-cache/a70a26391d4955d458aa1119a2d90bb743d6d1c3/zulip-venv/lib/python2.7/site-packages (from requests-oauthlib->python-twitter)
(zulip-venv)vagrant@vagrant-ubuntu-trusty-64:~$ python --version
Python 2.7.6
(zulip-venv)vagrant@vagrant-ubuntu-trusty-64:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import twitter
>>> exit()
(zulip-venv)vagrant@vagrant-ubuntu-trusty-64:~$ logout
Connection to 127.0.0.1 closed.
```
