### ISSUE TITLE
api.VerifyCredentials() is broken

### ISSUE THREAD

**Issue by imbellish** [bear/python-twitter#422]
Using python-twitter on this main.py file:

main.py

```
import twitter
import sqlalchemy as sql
import praw
import logging
import logging.config

from configparser import ConfigParser

# set up local config
CONFIG_PATH = '/usr/local/etc/<config-file>'
config = ConfigParser()
config.read(CONFIG_PATH)

# set up logging
logging.config.fileConfig(CONFIG_PATH)
log = logging.getLogger('root')

# twitter config
TW_CONSUMER_KEY = config.get('TWITTER', 'consumer_key')
TW_CONSUMER_SECRET = config.get('TWITTER', 'consumer_secret')
TW_ACCESS_TOKEN_KEY = config.get('TWITTER', 'access_token')
TW_ACCESS_TOKEN_SECRET = config.get('TWITTER', 'access_token_secret')

TW_API = twitter.Api(consumer_key=TW_CONSUMER_KEY,
                     consumer_secret=TW_ACCESS_TOKEN_SECRET,
                     access_token_key=TW_ACCESS_TOKEN_KEY,
                     access_token_secret=TW_ACCESS_TOKEN_SECRET)

api = TW_API
print(api.VerifyCredentials())
```

I get the following error: 

```
(env)imbellish@home:~/$ python -i src/main.py 
>>> TW_API
<twitter.api.Api object at 0x7ff6652e2b38>
>>> api = TW_API
>>> print(api.VerifyCredentials())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/imbellish/PycharmProjects/pdxgovbot/env/lib/python3.5/site-packages/twitter/api.py", line 4659, in VerifyCredentials
    resp = self._RequestUrl(url, 'GET', data)
  File "/home/imbellish/PycharmProjects/pdxgovbot/env/lib/python3.5/site-packages/twitter/api.py", line 4911, in _RequestUrl
    raise TwitterError("The twitter.Api instance must be authenticated.")
twitter.error.TwitterError: The twitter.Api instance must be authenticated.
```

Whereas using tweepy using the same configuration file, it works. 

main.py

```
import tweepy
import sqlalchemy as sql
import praw
import logging
import logging.config

from configparser import ConfigParser

# set up local config
CONFIG_PATH = '/usr/local/etc/<config-file>'
config = ConfigParser()
config.read(CONFIG_PATH)

# set up logging
logging.config.fileConfig(CONFIG_PATH)
log = logging.getLogger('root')

# twitter config
TW_CONSUMER_KEY = config.get('TWITTER', 'consumer_key')
TW_CONSUMER_SECRET = config.get('TWITTER', 'consumer_secret')
TW_ACCESS_TOKEN_KEY = config.get('TWITTER', 'access_token')
TW_ACCESS_TOKEN_SECRET = config.get('TWITTER', 'access_token_secret')

auth = tweepy.OAuthHandler(TW_CONSUMER_KEY, TW_CONSUMER_SECRET)
auth.set_access_token(TW_ACCESS_TOKEN_KEY, TW_ACCESS_TOKEN_SECRET)

TW_API = tweepy.API(auth)
api = TW_API
api.me()   # lots of output
```

Here's my output from `pip list`:

```
(env)imbellish@home:~/$ pip list
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
decorator (4.0.10)
future (0.16.0)
oauthlib (2.0.1)
pip (7.1.0)
praw (4.0.0)
praw-oauth2util (0.3.5)
prawcore (0.3.0)
requests (2.11.1)
requests-oauthlib (0.7.0)
setuptools (18.0.1)
six (1.10.0)
SQLAlchemy (1.1.4)
tweepy (3.5.0)
update-checker (0.15)
wheel (0.24.0)
```

And `python --version`:

`(env)imbellish@home:~/$ python --version
Python 3.5.2
`

And config file:

```
[DEFAULT]
logfile = ./logs/<application-name>
loglevel = DEBUG

[TWITTER]
consumer_key =
consumer_secret =
access_token =
access_token_secret =

[REDDIT]
consumer_key =
consumer_secret =
access_token =
access_token_secret =

[loggers]
keys=root

[handlers]
keys=hand01

[formatters]
keys=form01

[logger_root]
level=NOTSET
handlers=hand01

[handler_hand01]
class=FileHandler
level=%(loglevel)s
formatter=form01
args=('%(logfile)s', 'w')

[formatter_form01]
format=F1 %(asctime)s %(levelname)s %(message)s
datefmt=
class=logging.Formatter
```

**Comment by jeremylow** [comment]
```python
TW_API = twitter.Api(consumer_key=TW_CONSUMER_KEY,
                     consumer_secret=TW_ACCESS_TOKEN_SECRET,  # right here
                     access_token_key=TW_ACCESS_TOKEN_KEY,
                     access_token_secret=TW_ACCESS_TOKEN_SECRET)
```
You're assigning `TW_ACCESS_TOKEN_SECRET` to `consumer_secret`. Can you try it with this instantiation: 
```python
TW_API = twitter.Api(consumer_key=TW_CONSUMER_KEY,
                     consumer_secret=TW_CONSUMER_SECRET,
                     access_token_key=TW_ACCESS_TOKEN_KEY,
                     access_token_secret=TW_ACCESS_TOKEN_SECRET)
```

That said, you shouldn't be getting `twitter.error.TwitterError: The twitter.Api instance must be authenticated.`, you should be getting something like `TwitterError: [{'message': 'Could not authenticate you.', 'code': 32}]`

**Comment by jjescobaruni** [comment]
Hi! I'm getting same error I have already check that I was sending correct params. Here is my **code**:
`import settings

import twitter

api = twitter.Api(consumer_key=settings.twitter.get('APIKey'),
                  consumer_secret=settings.twitter.get('APIKeySecret'),
                  access_token_key=settings.twitter.get('AccessToken'),
                  access_token_secret=settings.twitter.get('AccessTokenSecret'))

print(api.VerifyCredentials())`

and follows is my **settings**:
`import configparser
config = configparser.ConfigParser()

config.read('settings.ini')

twitter =  {
    'APIKey': config.get('twitter', 'APIKey'),
    'APISecretKey': config.get('twitter', 'APISecretKey'),
    'AccessToken': config.get('twitter', 'AccessToken'),
    'AccessTokenSecret': config.get('twitter', 'AccessTokenSecret'),
}`

What have I been missing or doing wrong?

Thanks in advance!
