### ISSUE TITLE
TypeError with UsersLookup() 

### ISSUE THREAD

**Issue by affanshahid** [bear/python-twitter#446]
Getting: `TypeError: 'set' object does not support indexing` with the following code:

```python
followers = twitter.GetFollowerIDs(screen_name='guardian', total_count=10000)
print "got followers!"
users = twitter.UsersLookup(user_id=followers)
```

Output:
```bash
got followers!
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    users = twitter.UsersLookup(user_id=followers)
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 2869, in UsersLookup
    if len(t) == 1 and ('code' in t[0]) and (t[0]['code'] == 34):
TypeError: 'set' object does not support indexing
```

**Comment by jeremylow** [comment]
Fixed with https://github.com/bear/python-twitter/commit/0341e6031b4d8ab86608bb6a515b73ed19115acc
