### ISSUE TITLE
Error Message: Unauthorized

### ISSUE THREAD

**Issue by gascarcella** [bear/python-twitter#454]
I'm working in a proyect with your api. Everything was working OK since today, suddenly i'm starting having this error (without any code modifications)

`Process stream:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gabriel/Projects/twistreapy/twistrea.py", line 164, in Stream
    languages=langs):
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 4571, in GetStreamFilter
    data = self._ParseAndCheckTwitter(line.decode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 4859, in _ParseAndCheckTwitter
    raise TwitterError({'message': "Unauthorized"})
TwitterError: {'message': 'Unauthorized'}
`
I didn't changed any code, that's weird. Also if i clone my project to another computer with git, with exact same code, it's works on the other computer. 

I've spent 5 hours on trying to fix this but i didn't found how to

EDIT: i did more test, i've tested in two google cloud instances, both work's ok. I only get this error on my personal computer.

**Comment by klocatelli** [comment]
I also get this error on my personal computer. Haven't checked on another host yet.

This code snippet:

```python
import twitter
api = twitter.Api(consumer_key='XXX',
                  consumer_secret='XXX',
                  sleep_on_rate_limit=True,
                  application_only_auth=True)


results = api.GetRetweeters(X)
print(len(results)) # OK

for tweet in api.GetStreamSample(): # Fails
	print(tweet)
```

fails with this exception:
```python
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    for tweet in api.GetStreamSample():
  File "/Users/klocatelli/.virtualenvs/env1/lib/python2.7/site-packages/twitter/api.py", line 4540, in GetStreamSample
    data = self._ParseAndCheckTwitter(line.decode('utf-8'))
  File "/Users/klocatelli/.virtualenvs/env1/lib/python2.7/site-packages/twitter/api.py", line 4892, in _ParseAndCheckTwitter
    raise TwitterError({'message': "Unauthorized"})
twitter.error.TwitterError: {'message': 'Unauthorized'}
```

**Comment by jeremylow** [comment]
@klocatelli The `statuses/sample` endpoint requires user authentication. See here: https://dev.twitter.com/streaming/reference/get/statuses/sample
