### ISSUE TITLE
twitter.Api doesn't work

### ISSUE THREAD

**Issue by x30r** [bear/python-twitter#488]
Following is the error I am facing
```
>>> import twitter
>>> twitter.Api()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Api'
>>> twitter.api()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```
It was working with my previous application but now it is not even working with that.

**Comment by jeremylow** [comment]
Did you figure it out?

**Comment by x30r** [comment]
It was the issue with installing the package!

**Comment by iammoonchild** [comment]
I'm getting same error and unable to figure out what to do!
