### ISSUE TITLE
App Only authentication not working with Python3

### ISSUE THREAD

**Issue by Styx13** [bear/python-twitter#494]
Hello,

I am using python-twitter with pyhon3 and I tried to switched from the default user authentication to app authentication, and I first got the following error:

`Traceback (most recent call last):
  File "./python-twitterGraphDB.py", line 201, in <module>
    mta = MyTwitterAPI(consumer_key, consumer_secret, access_token, access_token_secret)
  File "./python-twitterGraphDB.py", line 114, in __init__
    self.api = twitter.Api(consumer_key, consumer_secret, access_token, access_token_secret, sleep_on_rate_limit=True, application_only_auth=True)
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 273, in __init__
    application_only_auth)
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 336, in SetCredentials
    self._bearer_token = self.GetAppOnlyAuthToken(consumer_key, consumer_secret)
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 291, in GetAppOnlyAuthToken
    from urllib import quote_plus
ImportError: cannot import name 'quote_plus'`

I figured out that's because with python3 urllib is split into parts and 'quote_plus' is now in urllib.parse

So I changed line 291 from `from urllib import quote_plus` to `from urllib.parse import quote_plus` and now get the following error:
`Traceback (most recent call last):
  File "./python-twitterGraphDB.py", line 201, in <module>
    mta = MyTwitterAPI(consumer_key, consumer_secret, access_token, access_token_secret)
  File "./python-twitterGraphDB.py", line 114, in __init__
    self.api = twitter.Api(consumer_key, consumer_secret, access_token, access_token_secret, sleep_on_rate_limit=True, application_only_auth=True)
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 273, in __init__
    application_only_auth)
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 336, in SetCredentials
    self._bearer_token = self.GetAppOnlyAuthToken(consumer_key, consumer_secret)
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 296, in GetAppOnlyAuthToken
    bearer_token = base64.b64encode('{}:{}'.format(key, secret))
  File "/usr/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'`

I tried to play a bit and use the `bytes('{}:{}'.format(key, secret), 'utf-8')` but unfortunately other errors shows up down the road.
So I guess there's more to it.

**Comment by Leftn** [comment]
I was able to get it working by encoding/decoding the string as needed

        bearer_token = base64.b64encode('{}:{}'.format(key, secret).encode("utf-8"))
        post_headers = {
            'Authorization': 'Basic ' + bearer_token.decode("utf-8"),
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
        }

**Comment by jeremylow** [comment]
lands in  8c5a036

**Comment by imarban** [comment]
Hey there!

I am using version 3.3 and I'm facing this issue. Is the solution present in 3.3 version?

**Comment by imarban** [comment]
I just realized this is not present in 3.3 but in 3.3.1. Do you have an estimated date for publishing version 3.3.1?
