### ISSUE TITLE
Estimated status length for "…" is 1 but twitter counts it as 2

### ISSUE THREAD

**Issue by d3d9** [bear/python-twitter#543]
Twitter counts "…" as two characters but python-twitter counts it as one.
Posting a tweet where this is a problem returns twitter response 186 instead of the usually expected "Text must be less than or equal to CHARACTER_LIMIT characters." error. (it doesn't matter where in the tweet the ellipsis is)

```
teststr = "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttes…"
print(len(teststr))
print(twitter.twitter_utils.calc_expected_status_length(teststr))
status = api.PostUpdate(teststr)
```
gives
```
280
280
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    status = api.PostUpdate(teststr)
  File "/usr/local/lib/python3.4/dist-packages/python_twitter-3.3.1-py3.4.egg/twitter/api.py", line 1111, in PostUpdate
  File "/usr/local/lib/python3.4/dist-packages/python_twitter-3.3.1-py3.4.egg/twitter/api.py", line 4996, in _ParseAndCheckTwitter
  File "/usr/local/lib/python3.4/dist-packages/python_twitter-3.3.1-py3.4.egg/twitter/api.py", line 5016, in _CheckForTwitterError
twitter.error.TwitterError: [{'code': 186, 'message': 'Tweet needs to be a bit shorter.'}]
```

**Comment by jeremylow** [comment]
fixed in cd52ca74eaa36b2ba4330f2fa41e844f95fbd485
