### ISSUE TITLE
The new character limit is 280, not 140

### ISSUE THREAD

**Issue by nachogoro** [bear/python-twitter#568]
I just got an exception when trying to post a 169-character-long status:

```
Traceback (most recent call last):
  File "./twitterbot.py", line 208, in <module>
    main()
  File "./twitterbot.py", line 198, in main
    to_reply.id)
  File "./twitterbot.py", line 90, in _safe_reply
    raise e
  File "./twitterbot.py", line 82, in _safe_reply
    in_reply_to_status_id=in_reply_to)
  File "/home/nacho/.pyenv/versions/twitter-bot/lib/python3.5/site-packages/twitter/api.py", line 1044, in PostUpdate
    raise TwitterError("Text must be less than or equal to 140 characters.")
twitter.error.TwitterError: Text must be less than or equal to 140 characters.
```
However, Twitter has been allowing 280-character-long messages for a while now.

**Comment by jeremylow** [comment]
Please upgrade to the newest version of the library (3.4.2)
