### ISSUE TITLE
twitter.error.TwitterError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]

### ISSUE THREAD

**Issue by PokestarFan** [bear/python-twitter#603]
Whenever I make a request with the api to fetch Direct Messages `api.GetDirectMessages()`, it always throws me a twittererror with the message "Sorry, that page does not exist."

Traceback:
```
Traceback (most recent call last):
  File "C:/Users/neela/Desktop/Programs/python projects/Mine/DM Storage/login.py", line 13, in <module>
    logging.info(api.GetDirectMessages())
  File "C:\Program Files\Python36\lib\site-packages\twitter\api.py", line 2937, in GetDirectMessages
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "C:\Program Files\Python36\lib\site-packages\twitter\api.py", line 4908, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "C:\Program Files\Python36\lib\site-packages\twitter\api.py", line 4928, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]
```

I tried looking through #592 , but it was closed at Nov. 2018, and the new endpoints should have been implemented. There have been four months since the closure, and how has there not been enough time to update the API endpoints?

**Comment by esemeniuc** [comment]
+1 have this problem

**Comment by PokestarFan** [comment]
Honestly if I knew how a token was received and then requested to the API I could send a push request to fix it.

**Comment by esemeniuc** [comment]
here's a quick hack to be able to use json: https://github.com/TrustedCapsules/python-twitter/commit/e0c90859e136a833d5bf7264438718f1b0cf85c2

The DirectMessage class needs to be updated (see https://github.com/TrustedCapsules/python-twitter/blob/e0c90859e136a833d5bf7264438718f1b0cf85c2/twitter/models.py#L180)

**Comment by theelk801** [comment]
Hi, I tried the fix and it didn't work, I just get the following:
`Traceback (most recent call last):
  File "[path_removed]/tweeting.py", line 13, in <module>
    api.GetDirectMessages()
  File "[path_removed]/twitter/api.py", line 2942, in GetDirectMessages
    return [DirectMessage.NewFromJsonDict(x) for x in data]
  File "[path_removed]/twitter/api.py", line 2942, in <listcomp>
    return [DirectMessage.NewFromJsonDict(x) for x in data]
  File "[path_removed]/twitter/models.py", line 88, in NewFromJsonDict
    json_data = data.copy()
AttributeError: 'str' object has no attribute 'copy'`

**Comment by esemeniuc** [comment]
@theelk801 You must use the return_json flag since the model hasnt been updated. Then you can manually manipulate the dict

**Comment by theelk801** [comment]
Oh, I see. Alright, I suppose that'll have to do for now.

**Comment by PokestarFan** [comment]
For anyone confused on how to implement the flag, it is `api.GetDirectMessages(return_json=True)` where api is the TwitterApi instance

**Comment by pacu** [comment]
I'm getting the same error 34 when trying to get DMs from an authorized App, even when I'm using the return_json parameter. :-/

**Comment by mdd423** [comment]
I am still having the same error in accessing DMs and neither the return_json parameter nor that quick hack fix work :/

**Comment by DVRodri8** [comment]
Hi guys, the Error is caused by the old version of pip package, in the pip version the function GetDirectMessages uses an old URL, you can change that for the new url.
Step 1:  find api.py file
run pip show python-twitter and see the path

Step 2: find the old url
in api.py, line 2922

Step 3:
change that line with
url = '%s/direct_messages/events/list.json' % self.base_url

**Comment by PokestarFan** [comment]
@DVRodri8  So you mean update the package?

**Comment by digital-mine** [comment]
just tried the @DVRodri8 fix but once updated the line 2922 of the api.py file I get this error:

`json_data = data.copy()
AttributeError: 'str' object has no attribute 'copy'`

**Comment by kevr** [comment]
Is there any kind of ETA or planning on getting this in the project?

**Comment by sebastiansam55** [comment]
> Hi guys, the Error is caused by the old version of pip package, in the pip version the function GetDirectMessages uses an old URL, you can change that for the new url.
> Step 1: find api.py file
> run pip show python-twitter and see the path
> 
> Step 2: find the old url
> in api.py, line 2922
> 
> Step 3:
> change that line with
> url = '%s/direct_messages/events/list.json' % self.base_url

This plus `return_json=True` made it work for me

**Comment by chrischma** [comment]
> > Hi guys, the Error is caused by the old version of pip package, in the pip version the function GetDirectMessages uses an old URL, you can change that for the new url.
> > Step 1: find api.py file
> > run pip show python-twitter and see the path
> > Step 2: find the old url
> > in api.py, line 2922
> > Step 3:
> > change that line with
> > url = '%s/direct_messages/events/list.json' % self.base_url
> 
> This plus `return_json=True` made it work for me

Can you specify this?

**Comment by digra1968** [comment]
{"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}
